site_name: better-sum
site_description:  Python's sum, minus ugly annotations and extra arguments.
docs_dir: docs

watch:
  - better_sum

# This theme seems to be the only way to get line numbers working
theme:
  name: material

markdown_extensions:
  - mkautodoc
  - admonition
  - pymdownx.highlight:
      linenums: true
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.snippets:
     auto_append:
      [ 'docs/_common_links.md' ]

nav:
  - Home: index.md
  - Usage Guide: usage.md
  - API Reference: api.md
  - Contributing: contributing.md
  - Why make this?: why.md


plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          show_signature_annotations: true
          options:
            show_source: false
            docstring_section_style: list
            show_root_heading: true
          import:
          - https://docs.python.org/3/objects.inv
          - https://typing-extensions.readthedocs.io/en/latest/objects.inv


